### ISSUE TITLE
[Chore] 개발 규칙

### ISSUE THREAD

**Issue by chamny20** [donga-st-b/frontend#2]
- [x] 브랜치명 규칙
- [x] 커밋 메시지 규칙
- [x] 이슈, 프로젝트, 마일스톤

**Comment by arinming** [comment]
## 커밋 메시지 규칙
[feat] : CICD 구축 (#1)

**Comment by chamny20** [comment]
[브랜치명 규칙]
ex) feature/1#kakao-login
